version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "spotify-blend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d5ex73jnwl4"
s3_prefix = "spotify-blend"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
